### ISSUE TITLE
EPIC: uplift current documentation

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/vortex#951]
https://docs.drevops.com/ has some docs added. We need to fill-in all the missing sections.

- [x] Diagram of build
- [ ] Diagram of site install
- [ ] CI docs
  - Caching of the database
  - Dind for consistency
  - Parallel runners for tests
  - Deployment regexes and tests for them
  - Setting up CI steps
  - Builder container
  - Build and test artifacts
- [x] Composer.json - features explained
- [ ] Drupal
  - Different approach to settings.php - single file + modules VS per-env file + modules etc.
  - More about settings:
    - Environment var definition
    - Global vs per env settings
    - Local settings
    - Include files for modules
  - Inline with drupal-project
  - Explain what each dependency does
  - Asset-manager
  - Explain to commit lock file after installing
  - Min stability
  - Explain platform
  - Theme scaffold:
    - Subtheme
    - Tests
    - Fe compilation
    - Components dir
    - Livereload
    - Sass
    - Grunt 
  - Module scaffold
    - Tests
    - Prevent sending emails
    - Enabling contribs for clam, search, redis 
- [ ] Database 
  - Didi vs difi workflows
  - Caching in ci
  - Sanitisation during install
- [ ] Test
  - Add allow fail vars
  - Add linting info
- [ ] Notifications
- [ ] Deployments (Setting up every type of the deployment)
- [ ] Explain example names like yoursite etc - maybe a separate section about installer

## Additional resources:

https://www.drupalasheville.com/sites/default/files/2020-07/Session%20-%20Taking%20Maximum%20Advantage%20of%20Drupal%20Core%27s%20Composer%20Template.pdf

**Comment by AlexSkrypnyk** [comment]
Closed in https://github.com/drevops/vortex/pull/1557 and https://github.com/drevops/vortex/pull/1558
